import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI, Type } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json());

// Lazy-loaded Gemini AI client to protect against crash on missing key
let aiInstance: GoogleGenAI | null = null;
function getGeminiClient(): GoogleGenAI {
  if (!aiInstance) {
    const key = process.env.GEMINI_API_KEY;
    if (!key) {
      throw new Error("GEMINI_API_KEY environment variable is required but missing. Please configure it in your Settings > Secrets panel.");
    }
    aiInstance = new GoogleGenAI({
      apiKey: key,
      httpOptions: {
        headers: {
          'User-Agent': 'aistudio-build',
        }
      }
    });
  }
  return aiInstance;
}

// Ensure the helper works smoothly
app.get("/api/health", (req, res) => {
  res.json({
    status: "ok",
    hasApiKey: !!process.env.GEMINI_API_KEY
  });
});

// Endpoint 1: Complete Resume Review
app.post("/api/counselor/review", async (req, res) => {
  try {
    const { cv } = req.body;
    if (!cv) {
      return res.status(400).json({ error: "Missing resume data (cv)." });
    }

    const ai = getGeminiClient();

    const reviewSchema = {
      type: Type.OBJECT,
      properties: {
        score: { type: Type.INTEGER, description: "Overall CV score from 0 to 100 based on standard tech resume guidelines" },
        summary: { type: Type.STRING, description: "A high-level professional evaluation in the persona of a friendly, elite tech carrier counselor" },
        strengths: { type: Type.ARRAY, items: { type: Type.STRING }, description: "3-5 key strengths found in their resume" },
        growthPoints: { type: Type.ARRAY, items: { type: Type.STRING }, description: "3-5 specific, actionable growth points / concrete improvement suggestions for computer science students" },
        atsKeywordsAnalysis: {
          type: Type.OBJECT,
          properties: {
            matched: { type: Type.ARRAY, items: { type: Type.STRING }, description: "Strong ATS keywords, technologies, languages, and frameworks matching technical standards already on the resume" },
            missingRecommended: { type: Type.ARRAY, items: { type: Type.STRING }, description: "Key missing recommended technical terms, paradigms, or CS terms that are highly valuable to add based on their experiences" }
          },
          required: ["matched", "missingRecommended"]
        },
        sectionScores: {
          type: Type.OBJECT,
          properties: {
            formattingAndStructure: { type: Type.INTEGER, description: "Readability, ATS layout, section clarity from 0 to 100" },
            experienceImpact: { type: Type.INTEGER, description: "Action verbs, Google XYZ metric measurement from 0 to 100" },
            technicalDepth: { type: Type.INTEGER, description: "Technology specificity, infrastructure keywords, scale from 0 to 100" },
            projectQuality: { type: Type.INTEGER, description: "Independent project rigor, architecture description from 0 to 100" }
          },
          required: ["formattingAndStructure", "experienceImpact", "technicalDepth", "projectQuality"]
        }
      },
      required: ["score", "summary", "strengths", "growthPoints", "atsKeywordsAnalysis", "sectionScores"]
    };

    const prompt = `You are an elite Tech Career Counselor and Former Technical Recruiter at top tier technology companies.
Analyze the following Computer Science student's resume data:
${JSON.stringify(cv, null, 2)}

Provide an exhaustive, professional critique in JSON structure matching the schema. Assess formatting, experience impact, technical specificity, and project solidity. Be constructive and specific: tell them exactly what technologies, metrics, or verbs to add.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: reviewSchema,
        temperature: 0.2
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response or empty text generated by Gemini.");
    }

    res.json(JSON.parse(text.trim()));
  } catch (error: any) {
    console.error("Error in /api/counselor/review:", error);
    res.status(500).json({ error: error.message || "Failed to analyze resume." });
  }
});

// Endpoint 2: Single Bullet Point Optimizer (XYZ Formula)
app.post("/api/counselor/improve-bullet", async (req, res) => {
  try {
    const { bullet, context } = req.body;
    if (!bullet) {
      return res.status(400).json({ error: "Missing bullet point string." });
    }

    const ai = getGeminiClient();

    const bulletImprovementSchema = {
      type: Type.OBJECT,
      properties: {
        suggestions: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              improvedBullet: { type: Type.STRING, description: "The full polished resume bullet point" },
              whyBetter: { type: Type.STRING, description: "Explanation of the change, e.g., what was added, verb enhancement, or metrics added" },
              impactVerbUsed: { type: Type.STRING, description: "The strong action verb used (e.g. Orchestrated, Engineered, Optimized, Containerized)" }
            },
            required: ["improvedBullet", "whyBetter", "impactVerbUsed"]
          }
        }
      },
      required: ["suggestions"]
    };

    const prompt = `You are a technical resume coach. Transform the following draft bullet point into 3 distinct, highly professional, ATS-optimized software engineering bullet alternatives.
Draft Bullet: "${bullet}"
Context / Tech Stack: "${context || 'Software Engineering / Computer Science'}"

Follow the Google XYZ format: 'Accomplished [X], as measured by [Y], by doing [Z]'. Keep the achievements realistic. If there are no clear metrics in the draft, add placeholder metrics (e.g. "[X]%", "[Y]ms") of realistic value and explain to the student to replace them with their own calculations.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: bulletImprovementSchema,
        temperature: 0.3
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response generated by Gemini.");
    }

    res.json(JSON.parse(text.trim()));
  } catch (error: any) {
    console.error("Error in /api/counselor/improve-bullet:", error);
    res.status(500).json({ error: error.message || "Failed to optimize bullet." });
  }
});

// Endpoint 3: Tailor Resume to Job Description
app.post("/api/counselor/tailor-resume", async (req, res) => {
  try {
    const { cv, jobDescription } = req.body;
    if (!cv || !jobDescription) {
      return res.status(400).json({ error: "Missing cv or jobDescription." });
    }

    const ai = getGeminiClient();

    const tailorSchema = {
      type: Type.OBJECT,
      properties: {
        strategicPitch: { type: Type.STRING, description: "A 2-3 sentence strategic pitch on how the candidate should market themselves specifically for this employer/role" },
        prioritizedKeywords: { type: Type.ARRAY, items: { type: Type.STRING }, description: "Keywords or tools from the job description that the candidate must make sure to highlight or add" },
        suggestedAdjustments: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              section: { type: Type.STRING, description: "Which specific section, project, or work experience to adjust (e.g., 'Technical Skills', 'Project: Grid Engine', or 'Work Experience: Web Intern')" },
              changeCategory: { type: Type.STRING, description: "Type of change (e.g., 'Emphasize Tech', 'Quantify Performance', 'Add Crucial Technical Tool')" },
              originalReference: { type: Type.STRING, description: "The original element, tool, or bullet as reference" },
              suggestedContent: { type: Type.STRING, description: "The customized adjusted version of the bullet or technical list" },
              explanation: { type: Type.STRING, description: "recruiter rationale: why this change explicitly checks a box in the job description" }
            },
            required: ["section", "changeCategory", "originalReference", "suggestedContent", "explanation"]
          }
        }
      },
      required: ["strategicPitch", "prioritizedKeywords", "suggestedAdjustments"]
    };

    const prompt = `You are an veteran software recruiter reviewing a resumes. A candidate is applying for this job:
Job Description:
${jobDescription}

With their current resume:
${JSON.stringify(cv, null, 2)}

Provide advice on exactly how to tailor this technical resume. Map their elements directly to the JD keywords and generate adjusted, precise tech-aligned bullets. Return JSON complying with the schema.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: tailorSchema,
        temperature: 0.3
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response generated by Gemini.");
    }

    res.json(JSON.parse(text.trim()));
  } catch (error: any) {
    console.error("Error in /api/counselor/tailor-resume:", error);
    res.status(500).json({ error: error.message || "Failed to tailor resume." });
  }
});

// Endpoint 4: Get Computer Science Starter Bullets
app.post("/api/counselor/generate-starter", async (req, res) => {
  try {
    const { topic } = req.body;
    if (!topic) {
      return res.status(400).json({ error: "Missing topic parameter." });
    }

    const ai = getGeminiClient();

    const starterSchema = {
      type: Type.OBJECT,
      properties: {
        recommendedTechStack: { type: Type.STRING, description: "Suggested comma-separated technologies to include for this project or role" },
        suggestedBullets: { type: Type.ARRAY, items: { type: Type.STRING }, description: "4 highly optimized XYZ bullet points that highlight technical complexity, concurrency, database performance, memory limits, or cloud infrastructure" }
      },
      required: ["recommendedTechStack", "suggestedBullets"]
    };

    const prompt = `You are a technical resume coach helping a computer science student write resume lines.
They want to add a project or internship containing: "${topic}".
Generate helper reference lines:
1. Recommended modern tech stack they should state (e.g. 'Golang, gRPC, Docker, Redis' or 'React, Tailwind, Node.js, PostgreSQL')
2. Four (4) outstanding, impact-filled bullet points outline typical software engineering achievements for this work. Frame using strong active verbs, and represent quantifiable dimensions (such as 'improving latency by 35%', 'scaling requests to 10k/sec', 'increasing API test coverage from 40% to 92%') so the student sees how to write high-impact lines.`;

    const response = await ai.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: starterSchema,
        temperature: 0.4
      }
    });

    const text = response.text;
    if (!text) {
      throw new Error("No response generated by Gemini.");
    }

    res.json(JSON.parse(text.trim()));
  } catch (error: any) {
    console.error("Error in /api/counselor/generate-starter:", error);
    res.status(500).json({ error: error.message || "Failed to generate starters." });
  }
});

// Server boot with Vite middleware configuration
async function startServer() {
  // Integrate Vite dynamically during development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    // Production serves static built files
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server is booting on port ${PORT}`);
  });
}

startServer();
